# Generated by Django 3.0.6 on 2020-11-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200, unique=True)),
                ('contact', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=400)),
                ('user_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
    ]
