# Generated by Django 3.0.6 on 2020-11-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employ', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=150, unique=True)),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField()),
                ('status', models.CharField(choices=[('1', 'Yet to Begin'), ('2', 'Started'), ('3', 'Completed')], max_length=100)),
            ],
        ),
    ]
